### ISSUE TITLE
Data import ERROR:  role "jupyterhub" does not exist

### ISSUE THREAD

**Issue by Pana** [graphprotocol/ens-rainbow#4] opened 2022-04-22 03:57 UTC

**Comment by Pana** [comment] 2022-04-22 07:29
Did I need to create jupyterhub role manually? What privilege does it need to grant ?

**Comment by schmidsi** [comment] 2023-05-18 11:41
I got error `ERROR:  role "jupyterhub" does not exist` when import rainbow table
My command : `zcat ens_names.sql.gz | psql -U suntzu -h 0.0.0.0 graph-node`

output :
```

SET
SET
SET
SET
SET
 set_config 
------------
 
(1 row)

SET
SET
SET
SET
ALTER TABLE
DROP TABLE
CREATE TABLE
COPY 133856895
ALTER TABLE
ERROR:  role "jupyterhub" does not exist
```

Reported by Suntzu Indexer: https://discord.com/channels/438038660412342282/737341252835737641/1108719811237781614

**Comment by lutter** [comment] 2023-05-18 18:41
That's on us, and a leftover from how the hosted service does things. We'll need to edit the SQL script so that it doesn't mention any specific user (or redump the tables in an appropriate way) so that indexers can import it with their normal `graph-node` user

**Comment by lutter** [comment] 2023-05-30 18:30
I just regenerated the file and updated the download to remove any mention of `jupyterhub`. Try redownloading and importing again (I also added a version compressed with `zstd`, though it's not a big difference)

When you import, make sure you import as the user that `graph-node` is using to make sure permissions within Postgres get set correctly.

**Comment by suntzu93** [comment] 2023-05-30 23:13
Thanks @lutter  , confirm I can import with new db without issue.

**Comment by schmidsi** [comment] 2023-05-31 11:09
Closing this since @suntzu93 confirmed it works. Feel free to reopen if issue still persists for you.

**Comment by azf20** [comment] 2023-05-31 11:22
Thanks!

**Closed by azf20** 2023-05-31 11:22 UTC
